### PR TITLE
ENH: Transition CI to GHA

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transition CI from TravisCI to GitHub Actions: add the corresponding GHA workflow file to test and package the tool.

Remove the TravisCI config file.

Discontinue testing on Python 2.7, 3.5, 3.6, and 3.7 as they all have reached their EOL and test on 3.9, 3.10, 3.11 and 3.12: https://devguide.python.org/versions/

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@demianw Some notes:
- Dependencies minimum versions probably need to be updated: the proposed workflow file will test the minimum dependencies, and it is likely that the current minimum versions will not work with recent Python versions.
- This PR will need to be merged in order to have the first CI runs.
- Prior to merging this PR it maybe be worthwhile tagging and releasing a version so that a pre-transition tag/release exists.

**Comment by demianw** [comment]
Dear @jhlegarreta great start ! Although I think that PRs should be merged into the main only when they are passing tests and working. 

I'd propose
1. a PR that transitions to versions 3.9, 3.10, 3.11 and 3.12 and passes the tests
2. a PR that moves from TravisCI to GHA

if you want to start from 2. then this one should keep, in the first version the whole system working, and we never have a non-functional master.

**Comment by jhlegarreta** [comment]
OK, starting with PR #52. Not sure why TravisCI is not notifying about the builds: is the project active on Travis ?

**Comment by demianw** [comment]
Seems that I have to re-setup travis. Didn't realise :) maybe start by migrating to GHA but keeping the current python versions ?

**Comment by jhlegarreta** [comment]
> maybe start by migrating to GHA but keeping the current python versions ?

A few thoughts on that:
- I'd dare to say that that no workflow (OS, Python, package version combination) will support Python < 3.8, extremely unlikely Python 2.x. Even if they did, we will only know once the branch is merged.
- If builds do not succeed, which I believe is likely to happen due to the above, unless you have a machine with Python < 3.8 and the bandwidth so as to fix things if anything fails, we are not likely to be able to fix those. I only have access to Python 3.8 and Python 3.10 on a Ubuntu 22.04 machine.

IMHO, I believe that there is little to no gain in trying to fix issues with versions that are not supported, but tagging/releasing a version at least allows to tell that a specific version worked at some point with a number of versions.

**Comment by jhlegarreta** [comment]
Closed in favor of #53.

**Pull request closed without merging**
