### PR TITLE
More Python 3 updates, fix #41

### LINKED ISSUE #44: TractQuerierSyntaxError
`https://github.com/demianw/tract_querier/blob/master/tract_querier/query_processor.py`: Ln 312

Often, there is an error arising `raise TractQuerierSyntaxError("Invalid query in line %d" % node.lineno)` which impedes the completion of tract querying. If we want to complete a query against a `.qry` file, what is the point of exiting before the complete query is done?

### PR DESCRIPTION
**Pull request by ihnorton**
Some more python 3 fixes, starting from #41. Fixes some ast usage issues (to fix #44), and various other errors we encountered running locally under python 3.

Also fixes several remaining nosetest failures, except this one below (I'll fix it later on):

```
======================================================================
FAIL: tract_querier.tests.test_query_rewrite.test_rewrite_notin_precedence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sw/miniconda36/envs/tract_querier/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/inorton/work/pnl/git/tract_querier/tract_querier/tests/test_query_rewrite.py", line 55, in test_rewrite_notin_precedence
    assert_equal(ast.dump(tree3), ast.dump(tree3_rw))
AssertionError: "Modu[15 chars]alue=BoolOp(op=And(), values=[Name(id='a', ctx[104 chars]))])" != "Modu[15 chars]alue=Compare(left=BoolOp(op=And(), values=[Nam[104 chars]))])"
Diff is 643 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

cc @tashrifbillah

### CODE REVIEW

**Comment by tashrifbillah** [comment]
Isaiah's fix successfully runs [pnlpipe](https://github.com/pnlbwh/pnlpipe/). So, we shall update our software against his pull request.

**Comment by tashrifbillah** [comment]
cc @demianw

**Comment by demianw** [comment]
@tashrifbillah @ihnorton great work! I will have time from wednesday to see that we can merge this PR ASAP.

**Comment by tashrifbillah** [comment]
Given a `.vtk` file and an `fsInDWI`, I have also checked the following equivalence between python2 and python 3 outputs. They agree.

```
	Query af.right: 000225
	Query cb.left: 000000
	Query cb.right: 000000
	Query cc: 000014
	Query cc_1: 000000
	Query cc_2: 000000
	Query cc_3: 000002
	Query cc_4: 000000
	Query cc_5: 000001
	Query cc_6: 000009
	Query cc_7: 000002
	Query cc_bankssts: 000000
	Query cc_caudalanteriorcingulate: 000000
	Query cc_caudalmiddlefrontal: 000411
	Query cc_cuneus: 000000
	Query cc_entorhinal: 000000
	Query cc_frontalpole: 000000
	Query cc_fusiform: 000000
	Query cc_inferiorparietal: 000000
	Query cc_inferiortemporal: 000000
	Query cc_insula: 000000
	Query cc_isthmuscingulate: 000000
	Query cc_lateraloccipital: 000000
	Query cc_lateralorbitofrontal: 000014
	Query cc_lingual: 000000
	Query cc_medialorbitofrontal: 000000
	Query cc_middletemporal: 000000
	Query cc_paracentral: 000000
	Query cc_parahippocampal: 000000
	Query cc_parsopercularis: 000002
	Query cc_parsorbitalis: 000000
	Query cc_parstriangularis: 000000
	Query cc_pericalcarine: 000000
	Query cc_postcentral: 000000
	Query cc_posteriorcingulate: 000000
	Query cc_precentral: 000000
	Query cc_precuneus: 000000
	Query cc_rostralanteriorcingulate: 000000
	Query cc_rostralmiddlefrontal: 003486
	Query cc_superiorfrontal: 001309
	Query cc_superiorparietal: 000000
	Query cc_superiortemporal: 000018
	Query cc_supramarginal: 000002
	Query cc_temporalpole: 000000
	Query cc_transversetemporal: 000002
	Query ccommisural: 005056
	Query cst.left: 000389
	Query cst.right: 000203
	Query ec.left: 000277
	Query ec.right: 000064
	Query extreme_capsule.left: 000114
	Query extreme_capsule.right: 000055
	Query ilf.left: 000000
	Query ilf.right: 000000
	Query internal_capsule_new.left: 000621
	Query internal_capsule_new.right: 000315
	Query ioff.left: 000037
	Query ioff.right: 000024
	Query mdlf.left: 000000
	Query mdlf.right: 000010
	Query slf_i.left: 000098
	Query slf_i.right: 000656
	Query slf_ii.left: 000147
	Query slf_ii.right: 000025
	Query slf_iii.left: 000013
	Query slf_iii.right: 000034
	Query soff.left: 000049
	Query soff.right: 000003
	Query striato_frontal.left: 000166
	Query striato_frontal.right: 000254
	Query striato_occipital.left: 000000
	Query striato_occipital.right: 000000
	Query striato_parietal.left: 000172
	Query striato_parietal.right: 000060
	Query thalamo_frontal.left: 000144
	Query thalamo_frontal.right: 000218
	Query thalamo_occipital.left: 000008
	Query thalamo_occipital.right: 000006
	Query thalamo_parietal.left: 000145
	Query thalamo_parietal.right: 000083
	Query uf.left: 000007
	Query uf.right: 000000
```

**Comment by tashrifbillah** [comment]
@demianw , how is going with the PR?

**Comment by tashrifbillah** [comment]
Cool, now I guess we should be good to merge this PR!

**Comment by demianw** [comment]
Finally found the time to complete this PR and merge it. Thanks for your work @tashrifbillah and @ihnorton !!!!

**Pull request merged**
